const footerContent = {
  en: {
    brand: "Sudais Azlan",
    description: "Passionate AI Engineer and Software Developer. Exploring innovative solutions and cutting-edge technologies.",
    links: [
      { href: "/", label: "Home" },
      { href: "/about", label: "About" },
      { href: "/projects", label: "Projects" },
      { href: "/blogs", label: "Blogs" },
      { href: "/privacy-policy", label: "Privacy Policy" },
      { href: "/contact", label: "Contact" },
      { href: "/help", label: "Help" },
      { href: "/faq", label: "FAQ" },
      { href: "/waitlist", label: "Join Waitlist" },
    ],
    copyright: "© 2025 Sudais Azlan. All rights reserved.",
  },
  es: {
    brand: "Sudais Azlan",
    description: "Apasionado ingeniero de IA y desarrollador de software. Explorando soluciones innovadoras y tecnologías de vanguardia.",
    links: [
      { href: "/", label: "Inicio" },
      { href: "/about", label: "Acerca de" },
      { href: "/projects", label: "Proyectos" },
      { href: "/blogs", label: "Blogs" },
      { href: "/privacy-policy", label: "Política de Privacidad" },
      { href: "/contact", label: "Contacto" },
      { href: "/help", label: "Ayuda" },
      { href: "/faq", label: "Preguntas Frecuentes" },
      { href: "/waitlist", label: "Unirse a la lista de espera" },
    ],
    copyright: "© 2025 Sudais Azlan. Todos los derechos reservados.",
  },
  fr: {
    brand: "Sudais Azlan",
    description: "Ingénieur IA passionné et développeur logiciel. Explorer des solutions innovantes et des technologies de pointe.",
    links: [
      { href: "/", label: "Accueil" },
      { href: "/about", label: "À propos" },
      { href: "/projects", label: "Projets" },
      { href: "/blogs", label: "Blogs" },
      { href: "/privacy-policy", label: "Politique de Confidentialité" },
      { href: "/contact", label: "Contact" },
      { href: "/help", label: "Aide" },
      { href: "/faq", label: "FAQ" },
      { href: "/waitlist", label: "Rejoindre la liste d'attente" },
    ],
    copyright: "© 2025 Sudais Azlan. Tous droits réservés.",
  },
  de: {
    brand: "Sudais Azlan",
    description: "Leidenschaftlicher KI-Ingenieur und Softwareentwickler. Erforschung innovativer Lösungen und modernster Technologien.",
    links: [
      { href: "/", label: "Startseite" },
      { href: "/about", label: "Über mich" },
      { href: "/projects", label: "Projekte" },
      { href: "/blogs", label: "Blogs" },
      { href: "/privacy-policy", label: "Datenschutz" },
      { href: "/contact", label: "Kontakt" },
      { href: "/help", label: "Hilfe" },
      { href: "/faq", label: "FAQ" },
      { href: "/waitlist", label: "Warteliste beitreten" },
    ],
    copyright: "© 2025 Sudais Azlan. Alle Rechte vorbehalten.",
  },
  it: {
    brand: "Sudais Azlan",
    description: "Appassionato ingegnere AI e sviluppatore software. Esplorando soluzioni innovative e tecnologie all'avanguardia.",
    links: [
      { href: "/", label: "Home" },
      { href: "/about", label: "Chi sono" },
      { href: "/projects", label: "Progetti" },
      { href: "/blogs", label: "Blog" },
      { href: "/privacy-policy", label: "Privacy Policy" },
      { href: "/contact", label: "Contatto" },
      { href: "/help", label: "Aiuto" },
      { href: "/faq", label: "FAQ" },
      { href: "/waitlist", label: "Unisciti alla lista d'attesa" },
    ],
    copyright: "© 2025 Sudais Azlan. Tutti i diritti riservati.",
  },
  pt: {
    brand: "Sudais Azlan",
    description: "Engenheiro de IA e desenvolvedor de software apaixonado. Explorando soluções inovadoras e tecnologias de ponta.",
    links: [
      { href: "/", label: "Início" },
      { href: "/about", label: "Sobre" },
      { href: "/projects", label: "Projetos" },
      { href: "/blogs", label: "Blogs" },
      { href: "/privacy-policy", label: "Política de Privacidade" },
      { href: "/contact", label: "Contato" },
      { href: "/help", label: "Ajuda" },
      { href: "/faq", label: "FAQ" },
      { href: "/waitlist", label: "Entrar na lista de espera" },
    ],
    copyright: "© 2025 Sudais Azlan. Todos os direitos reservados.",
  },
  ru: {
    brand: "Sudais Azlan",
    description: "Увлечённый инженер по ИИ и разработчик программного обеспечения. Изучение инновационных решений и передовых технологий.",
    links: [
      { href: "/", label: "Главная" },
      { href: "/about", label: "Обо мне" },
      { href: "/projects", label: "Проекты" },
      { href: "/blogs", label: "Блоги" },
      { href: "/privacy-policy", label: "Политика конфиденциальности" },
      { href: "/contact", label: "Контакты" },
      { href: "/help", label: "Помощь" },
      { href: "/faq", label: "Вопросы и ответы" },
      { href: "/waitlist", label: "Присоединиться к списку ожидания" },
    ],
    copyright: "© 2025 Sudais Azlan. Все права защищены.",
  },
  ja: {
    brand: "Sudais Azlan",
    description: "情熱的なAIエンジニア兼ソフトウェア開発者。革新的なソリューションと最先端技術を探求しています。",
    links: [
      { href: "/", label: "ホーム" },
      { href: "/about", label: "私について" },
      { href: "/projects", label: "プロジェクト" },
      { href: "/blogs", label: "ブログ" },
      { href: "/privacy-policy", label: "プライバシーポリシー" },
      { href: "/contact", label: "お問い合わせ" },
      { href: "/help", label: "ヘルプ" },
      { href: "/faq", label: "よくある質問" },
      { href: "/waitlist", label: "ウェイトリストに参加" },
    ],
    copyright: "© 2025 Sudais Azlan. 無断転載を禁じます。",
  },
  ko: {
    brand: "Sudais Azlan",
    description: "열정적인 AI 엔지니어 및 소프트웨어 개발자. 혁신적인 솔루션과 최첨단 기술을 탐구합니다.",
    links: [
      { href: "/", label: "홈" },
      { href: "/about", label: "소개" },
      { href: "/projects", label: "프로젝트" },
      { href: "/blogs", label: "블로그" },
      { href: "/privacy-policy", label: "개인정보처리방침" },
      { href: "/contact", label: "문의" },
      { href: "/help", label: "도움말" },
      { href: "/faq", label: "자주 묻는 질문" },
      { href: "/waitlist", label: "웨이팅리스트 참여" },
    ],
    copyright: "© 2025 Sudais Azlan. 모든 권리 보유.",
  },
  ar: {
    brand: "سودايس أزلان",
    description: "مهندس برمجيات ومهندس ذكاء اصطناعي شغوف. استكشاف حلول مبتكرة وتقنيات متقدمة.",
    links: [
      { href: "/", label: "الرئيسية" },
      { href: "/about", label: "عني" },
      { href: "/projects", label: "المشاريع" },
      { href: "/blogs", label: "المدونات" },
      { href: "/privacy-policy", label: "سياسة الخصوصية" },
      { href: "/contact", label: "اتصل" },
      { href: "/help", label: "مساعدة" },
      { href: "/faq", label: "الأسئلة الشائعة" },
      { href: "/waitlist", label: "انضم إلى قائمة الانتظار" },
    ],
    copyright: "© 2025 سودايس أزلان. جميع الحقوق محفوظة.",
  },
  zh: {
    brand: "Sudais Azlan",
    description: "充满热情的人工智能工程师和软件开发人员。探索创新解决方案和前沿技术。",
    links: [
      { href: "/", label: "首页" },
      { href: "/about", label: "关于我" },
      { href: "/projects", label: "项目" },
      { href: "/blogs", label: "博客" },
      { href: "/privacy-policy", label: "隐私政策" },
      { href: "/contact", label: "联系" },
      { href: "/help", label: "帮助" },
      { href: "/faq", label: "常见问题" },
      { href: "/waitlist", label: "加入候补名单" },
    ],
    copyright: "© 2025 Sudais Azlan. 保留所有权利。",
  },
  hi: {
    brand: "सुदाइस अज़लान",
    description: "जुनूनी एआई इंजीनियर और सॉफ्टवेयर डेवलपर। नवीन समाधान और अत्याधुनिक तकनीकों का अन्वेषण।",
    links: [
      { href: "/", label: "होम" },
      { href: "/about", label: "मेरे बारे में" },
      { href: "/projects", label: "प्रोजेक्ट्स" },
      { href: "/blogs", label: "ब्लॉग्स" },
      { href: "/privacy-policy", label: "गोपनीयता नीति" },
      { href: "/contact", label: "संपर्क करें" },
      { href: "/help", label: "सहायता" },
      { href: "/faq", label: "सामान्य प्रश्न" },
      { href: "/waitlist", label: "वेटलिस्ट में शामिल हों" },
    ],
    copyright: "© 2025 सुदाइस अज़लान. सर्वाधिकार सुरक्षित।",
  },
  bn: {
    brand: "সুদাইস আজলান",
    description: "উৎসাহী এআই ইঞ্জিনিয়ার এবং সফটওয়্যার ডেভেলপার। উদ্ভাবনী সমাধান এবং আধুনিক প্রযুক্তি অনুসন্ধান।",
    links: [
      { href: "/", label: "হোম" },
      { href: "/about", label: "আমার সম্পর্কে" },
      { href: "/projects", label: "প্রকল্পসমূহ" },
      { href: "/blogs", label: "ব্লগ" },
      { href: "/privacy-policy", label: "গোপনীয়তা নীতি" },
      { href: "/contact", label: "যোগাযোগ" },
      { href: "/help", label: "সহায়তা" },
      { href: "/faq", label: "প্রশ্নাবলী" },
      { href: "/waitlist", label: "ওয়েটলিস্টে যোগ দিন" },
    ],
    copyright: "© 2025 সুদাইস আজলান. সর্বস্বত্ব সংরক্ষিত।",
  },
  pa: {
    brand: "ਸੁਦੈਸ ਅਜ਼ਲਾਨ",
    description: "ਜਜ਼ਬੇ ਨਾਲ ਭਰਪੂਰ ਏਆਈ ਇੰਜੀਨੀਅਰ ਅਤੇ ਸਾਫਟਵੇਅਰ ਡਿਵੈਲਪਰ। ਨਵੀਂ ਸੋਚ ਵਾਲੇ ਹੱਲ ਅਤੇ ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀਆਂ ਦੀ ਖੋਜ।",
    links: [
      { href: "/", label: "ਮੁੱਖ ਪੰਨਾ" },
      { href: "/about", label: "ਮੇਰੇ ਬਾਰੇ" },
      { href: "/projects", label: "ਪਰੋਜੈਕਟ" },
      { href: "/blogs", label: "ਬਲੌਗ" },
      { href: "/privacy-policy", label: "ਪਰਦੇਦਾਰੀ ਨੀਤੀ" },
      { href: "/contact", label: "ਸੰਪਰਕ ਕਰੋ" },
      { href: "/help", label: "ਮਦਦ" },
      { href: "/faq", label: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ" },
      { href: "/waitlist", label: "ਵੈਟਲਿਸਟ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ" },
    ],
    copyright: "© 2025 ਸੁਦੈਸ ਅਜ਼ਲਾਨ. ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
  },
  vi: {
    brand: "Sudais Azlan",
    description: "Kỹ sư AI và nhà phát triển phần mềm đầy đam mê. Khám phá các giải pháp sáng tạo và công nghệ tiên tiến.",
    links: [
      { href: "/", label: "Trang chủ" },
      { href: "/about", label: "Về tôi" },
      { href: "/projects", label: "Dự án" },
      { href: "/blogs", label: "Blog" },
      { href: "/privacy-policy", label: "Chính sách bảo mật" },
      { href: "/contact", label: "Liên hệ" },
      { href: "/help", label: "Trợ giúp" },
      { href: "/faq", label: "Câu hỏi thường gặp" },
      { href: "/waitlist", label: "Tham gia danh sách chờ" },
    ],
    copyright: "© 2025 Sudais Azlan. Đã đăng ký bản quyền.",
  },
  id: {
    brand: "Sudais Azlan",
    description: "Insinyur AI dan Pengembang Perangkat Lunak yang Penuh Semangat. Menjelajahi solusi inovatif dan teknologi mutakhir.",
    links: [
      { href: "/", label: "Beranda" },
      { href: "/about", label: "Tentang Saya" },
      { href: "/projects", label: "Proyek" },
      { href: "/blogs", label: "Blog" },
      { href: "/privacy-policy", label: "Kebijakan Privasi" },
      { href: "/contact", label: "Kontak" },
      { href: "/help", label: "Bantuan" },
      { href: "/faq", label: "FAQ" },
      { href: "/waitlist", label: "Gabung Daftar Tunggu" },
    ],
    copyright: "© 2025 Sudais Azlan. Hak cipta dilindungi undang-undang.",
  },
  tr: {
    brand: "Sudais Azlan",
    description: "Tutkulu Yapay Zeka Mühendisi ve Yazılım Geliştirici. Yenilikçi çözümler ve son teknolojiler üzerine çalışıyor.",
    links: [
      { href: "/", label: "Ana Sayfa" },
      { href: "/about", label: "Hakkımda" },
      { href: "/projects", label: "Projeler" },
      { href: "/blogs", label: "Bloglar" },
      { href: "/privacy-policy", label: "Gizlilik Politikası" },
      { href: "/contact", label: "İletişim" },
      { href: "/help", label: "Yardım" },
      { href: "/faq", label: "SSS" },
      { href: "/waitlist", label: "Bekleme Listesine Katıl" },
    ],
    copyright: "© 2025 Sudais Azlan. Tüm hakları saklıdır.",
  },
  fa: {
    brand: "سودایس ازلان",
    description: "مهندس هوش مصنوعی و توسعه‌دهنده نرم‌افزار پرشور. بررسی راه‌حل‌های نوآورانه و فناوری‌های پیشرفته.",
    links: [
      { href: "/", label: "خانه" },
      { href: "/about", label: "درباره من" },
      { href: "/projects", label: "پروژه‌ها" },
      { href: "/blogs", label: "بلاگ‌ها" },
      { href: "/privacy-policy", label: "سیاست حفظ حریم خصوصی" },
      { href: "/contact", label: "تماس" },
      { href: "/help", label: "راهنما" },
      { href: "/faq", label: "سؤالات متداول" },
      { href: "/waitlist", label: "پیوستن به لیست انتظار" },
    ],
    copyright: "© 2025 سودایس ازلان. کلیه حقوق محفوظ است.",
  },
  ta: {
    brand: "சுடைஸ் அஸ்லான்",
    description: "ஆர்வமுள்ள செயற்கை நுண்ணறிவு பொறியாளர் மற்றும் மென்பொருள் டெவலப்பர். புதுமையான தீர்வுகள் மற்றும் முன்னணி தொழில்நுட்பங்களை ஆராய்கிறேன்.",
    links: [
      { href: "/", label: "முகப்பு" },
      { href: "/about", label: "என்னை பற்றி" },
      { href: "/projects", label: "திட்டங்கள்" },
      { href: "/blogs", label: "வலைப்பதிவுகள்" },
      { href: "/privacy-policy", label: "தனியுரிமைக் கொள்கை" },
      { href: "/contact", label: "தொடர்பு" },
      { href: "/help", label: "உதவி" },
      { href: "/faq", label: "அடிக்கடி கேட்கப்படும் கேள்விகள்" },
      { href: "/waitlist", label: "வெயிட்லிஸ்டில் சேரவும்" },
    ],
    copyright: "© 2025 சுடைஸ் அஸ்லான். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
  },
  te: {
    brand: "సుడాయిస్ అజ్లాన్",
    description: "ఆవేశభరిత AI ఇంజనీర్ మరియు సాఫ్ట్‌వేర్ డెవలపర్. వినూత్న పరిష్కారాలు మరియు ఆధునిక సాంకేతికతలను అన్వేషించండి.",
    links: [
      { href: "/", label: "హోమ్" },
      { href: "/about", label: "నా గురించి" },
      { href: "/projects", label: "ప్రాజెక్ట్స్" },
      { href: "/blogs", label: "బ్లాగ్స్" },
      { href: "/privacy-policy", label: "గోప్యతా విధానం" },
      { href: "/contact", label: "సంప్రదించండి" },
      { href: "/help", label: "సహాయం" },
      { href: "/faq", label: "తరచుగా అడిగే ప్రశ్నలు" },
      { href: "/waitlist", label: "వెయిట్లిస్ట్‌లో చేరండి" },
    ],
    copyright: "© 2025 సుడాయిస్ అజ్లాన్. అన్ని హక్కులు పరిరక్షించబడ్డాయి.",
  },
  mr: {
    brand: "सुदाइस अझलान",
    description: "उत्साही एआय अभियंता आणि सॉफ्टवेअर विकसक. नाविन्यपूर्ण उपाय आणि अत्याधुनिक तंत्रज्ञानाचा शोध.",
    links: [
      { href: "/", label: "मुख्यपृष्ठ" },
      { href: "/about", label: "माझ्याबद्दल" },
      { href: "/projects", label: "प्रकल्प" },
      { href: "/blogs", label: "ब्लॉग्स" },
      { href: "/privacy-policy", label: "गोपनीयता धोरण" },
      { href: "/contact", label: "संपर्क" },
      { href: "/help", label: "मदत" },
      { href: "/faq", label: "नेहमी विचारले जाणारे प्रश्न" },
      { href: "/waitlist", label: "वेटलिस्टमध्ये सामील व्हा" },
    ],
    copyright: "© 2025 सुदाइस अझलान. सर्व हक्क राखीव.",
  },
  ur: {
    brand: "سودیس اذلان",
    description: "جذبہ رکھنے والا اے آئی انجینئر اور سافٹ ویئر ڈویلپر۔ جدید حل اور جدید ترین ٹیکنالوجیز کی تلاش۔",
    links: [
      { href: "/", label: "ہوم" },
      { href: "/about", label: "میرے بارے میں" },
      { href: "/projects", label: "پروجیکٹس" },
      { href: "/blogs", label: "بلاگز" },
      { href: "/privacy-policy", label: "پرائیویسی پالیسی" },
      { href: "/contact", label: "رابطہ کریں" },
      { href: "/help", label: "مدد" },
      { href: "/faq", label: "عمومی سوالات" },
      { href: "/waitlist", label: "ویٹ لسٹ میں شامل ہوں" },
    ],
    copyright: "© 2025 سودیس اذلان. جملہ حقوق محفوظ ہیں.",
  },
  sw: {
    brand: "Sudais Azlan",
    description: "Mhandisi wa AI mwenye shauku na Msanidi Programu. Kuchunguza suluhisho bunifu na teknolojia za kisasa.",
    links: [
      { href: "/", label: "Nyumbani" },
      { href: "/about", label: "Kuhusu Mimi" },
      { href: "/projects", label: "Miradi" },
      { href: "/blogs", label: "Blogu" },
      { href: "/privacy-policy", label: "Sera ya Faragha" },
      { href: "/contact", label: "Wasiliana" },
      { href: "/help", label: "Msaada" },
      { href: "/faq", label: "Maswali Yanayoulizwa Mara kwa Mara" },
      { href: "/waitlist", label: "Jiunge na Orodha ya Kusubiri" },
    ],
    copyright: "© 2025 Sudais Azlan. Haki zote zimehifadhiwa.",
  },
  th: {
    brand: "Sudais Azlan",
    description: "วิศวกร AI และนักพัฒนาซอฟต์แวร์ที่เต็มไปด้วยความหลงใหล สำรวจวิธีแก้ปัญหาที่สร้างสรรค์และเทคโนโลยีล้ำสมัย",
    links: [
      { href: "/", label: "หน้าหลัก" },
      { href: "/about", label: "เกี่ยวกับฉัน" },
      { href: "/projects", label: "โปรเจกต์" },
      { href: "/blogs", label: "บล็อก" },
      { href: "/privacy-policy", label: "นโยบายความเป็นส่วนตัว" },
      { href: "/contact", label: "ติดต่อ" },
      { href: "/help", label: "ช่วยเหลือ" },
      { href: "/faq", label: "คำถามที่พบบ่อย" },
      { href: "/waitlist", label: "เข้าร่วมรายชื่อรอ" },
    ],
    copyright: "© 2025 Sudais Azlan. สงวนลิขสิทธิ์.",
  },
  ms: {
    brand: "Sudais Azlan",
    description: "Jurutera AI dan Pembangun Perisian yang Bersemangat. Meneroka penyelesaian inovatif dan teknologi terkini.",
    links: [
      { href: "/", label: "Laman Utama" },
      { href: "/about", label: "Tentang Saya" },
      { href: "/projects", label: "Projek" },
      { href: "/blogs", label: "Blog" },
      { href: "/privacy-policy", label: "Dasar Privasi" },
      { href: "/contact", label: "Hubungi" },
      { href: "/help", label: "Bantuan" },
      { href: "/faq", label: "Soalan Lazim" },
      { href: "/waitlist", label: "Sertai Senarai Menunggu" },
    ],
    copyright: "© 2025 Sudais Azlan. Hak cipta terpelihara.",
  },
  gu: {
    brand: "સુદૈસ અઝલાન",
    description: "ઉત્સાહી એઆઇ ઇજનેર અને સોફ્ટવેર ડેવલપર. નવીન સોલ્યુશન્સ અને અદ્યતન ટેક્નોલોજી શોધો.",
    links: [
      { href: "/", label: "હોમ" },
      { href: "/about", label: "મારા વિશે" },
      { href: "/projects", label: "પ્રોજેક્ટ્સ" },
      { href: "/blogs", label: "બ્લોગ્સ" },
      { href: "/privacy-policy", label: "ગોપનીયતા નીતિ" },
      { href: "/contact", label: "સંપર્ક કરો" },
      { href: "/help", label: "મદદ" },
      { href: "/faq", label: "વારંવાર પૂછાતા પ્રશ્નો" },
      { href: "/waitlist", label: "વેઇટલિસ્ટમાં જોડાઓ" },
    ],
    copyright: "© 2025 સુદૈસ અઝલાન. સર્વાધિકાર સુરક્ષિત.",
  },
  kn: {
    brand: "ಸುಡೈಸ್ ಅಝ್ಲಾನ್",
    description: "ಆಸಕ್ತಿಯುಳ್ಳ AI ಎಂಜಿನಿಯರ್ ಮತ್ತು ಸಾಫ್ಟ್‌ವೇರ್ ಡೆವಲಪರ್. ನವೀನ ಪರಿಹಾರಗಳು ಮತ್ತು ಆಧುನಿಕ ತಂತ್ರಜ್ಞಾನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    links: [
      { href: "/", label: "ಮುಖಪುಟ" },
      { href: "/about", label: "ನನ್ನ ಬಗ್ಗೆ" },
      { href: "/projects", label: "ಪ್ರಾಜೆಕ್ಟ್ಸ್" },
      { href: "/blogs", label: "ಬ್ಲಾಗ್ಸ್" },
      { href: "/privacy-policy", label: "ಗೌಪ್ಯತಾ ನೀತಿ" },
      { href: "/contact", label: "ಸಂಪರ್ಕಿಸಿ" },
      { href: "/help", label: "ಸಹಾಯ" },
      { href: "/faq", label: "ಪದೇಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು" },
      { href: "/waitlist", label: "ವೇಟ್ಲಿಸ್ಟ್‌ಗೆ ಸೇರಿ" },
    ],
    copyright: "© 2025 ಸುಡೈಸ್ ಅಝ್ಲಾನ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
  },
  ml: {
    brand: "സുഡൈസ് അസ്ലാൻ",
    description: "ആവേശമുള്ള AI എഞ്ചിനീയറും സോഫ്റ്റ്‌വെയർ ഡെവലപ്പറും. നവീന പരിഹാരങ്ങളും cutting-edge ടെക്‌നോളജികളും അന്വേഷിക്കുന്നു.",
    links: [
      { href: "/", label: "ഹോം" },
      { href: "/about", label: "എന്നെ കുറിച്ച്" },
      { href: "/projects", label: "പ്രോജക്ടുകൾ" },
      { href: "/blogs", label: "ബ്ലോഗുകൾ" },
      { href: "/privacy-policy", label: "സ്വകാര്യതാ നയം" },
      { href: "/contact", label: "ബന്ധപ്പെടുക" },
      { href: "/help", label: "സഹായം" },
      { href: "/faq", label: "അടിക്കടി ചോദിക്കുന്ന ചോദ്യങ്ങൾ" },
      { href: "/waitlist", label: "വെയ്റ്റ്‌ലിസ്റ്റിൽ ചേരുക" },
    ],
    copyright: "© 2025 സുഡൈസ് അസ്ലാൻ. എല്ലാ അവകാശങ്ങളും സംരക്ഷിച്ചിരിക്കുന്നു.",
  },
  or: {
    brand: "Sudais Azlan",
    description: "ଉତ୍ସାହୀ AI ଇଞ୍ଜିନିୟର୍ ଏବଂ ସଫ୍ଟୱେର୍ ବିକାଶକାରୀ। ନୂତନ ସମାଧାନ ଏବଂ ଆଧୁନିକ ପ୍ରଯୁକ୍ତି ଅନ୍ୱେଷଣ।",
    links: [
      { href: "/", label: "ମୂଳପୃଷ୍ଠା" },
      { href: "/about", label: "ମୋ ବିଷୟରେ" },
      { href: "/projects", label: "ପ୍ରକଳ୍ପଗୁଡ଼ିକ" },
      { href: "/blogs", label: "ବ୍ଲଗ୍" },
      { href: "/privacy-policy", label: "ଗୋପନୀୟତା ନୀତି" },
      { href: "/contact", label: "ଯୋଗାଯୋଗ" },
      { href: "/help", label: "ସହଯୋଗ" },
      { href: "/faq", label: "ପ୍ରଶ୍ନୋତ୍ତର" },
      { href: "/waitlist", label: "ଅପେକ୍ଷା ତାଲିକାରେ ଯୋଗଦିଅନ୍ତୁ" },
    ],
    copyright: "© 2025 Sudais Azlan. ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ।",
  },
  si: {
    brand: "Sudais Azlan",
    description: "උද්යෝගිමත් AI ඉංජිනේරු සහ මෘදුකාංග සංවර්ධක. නවෝත්පාදන විසඳුම් සහ නවීන තාක්ෂණය පරීක්ෂා කරයි.",
    links: [
      { href: "/", label: "මුල් පිටුව" },
      { href: "/about", label: "මගේ ගැන" },
      { href: "/projects", label: "ව්‍යාපෘති" },
      { href: "/blogs", label: "බ්ලොග්" },
      { href: "/privacy-policy", label: "රහස්‍යතා ප්‍රතිපත්තිය" },
      { href: "/contact", label: "සම්බන්ධ වන්න" },
      { href: "/help", label: "උදව්" },
      { href: "/faq", label: "නිතර අසන ප්‍රශ්න" },
      { href: "/waitlist", label: "රැඳී සිටින ලැයිස්තුවට එක්වන්න" },
    ],
    copyright: "© 2025 Sudais Azlan. සියලුම හිමිකම් ඇවිරිණි.",
  },
  ps: {
    brand: "Sudais Azlan",
    description: "پرعزم AI انجنیر او سافټویر پراختیا کونکی. نوښتګر حلونه او پرمختللي ټیکنالوژي لټول.",
    links: [
      { href: "/", label: "کور" },
      { href: "/about", label: "زما په اړه" },
      { href: "/projects", label: "پروژې" },
      { href: "/blogs", label: "بلاګونه" },
      { href: "/privacy-policy", label: "د محرمیت تګلاره" },
      { href: "/contact", label: "اړیکه" },
      { href: "/help", label: "مرسته" },
      { href: "/faq", label: "پرله پسې پوښتنې" },
      { href: "/waitlist", label: "د انتظار لیست ته ورشئ" },
    ],
    copyright: "© 2025 Sudais Azlan. ټول حقوق خوندي دي.",
  },
};

export default footerContent;
