export const brandNamesAllLanguages = [
  { language: "English", code: "en", value: "CODEWITHAZLAN" },
  { language: "Spanish", code: "es", value: "CODEWITHAZLAN" },
  { language: "French", code: "fr", value: "CODEWITHAZLAN" },
  { language: "German", code: "de", value: "CODEWITHAZLAN" },
  { language: "Italian", code: "it", value: "CODEWITHAZLAN" },
  { language: "Portuguese", code: "pt", value: "CODEWITHAZLAN" },
  { language: "Russian", code: "ru", value: "КОДЕВИТХАЗЛАН" },
  { language: "Japanese", code: "ja", value: "コードウィズアズラン" },
  { language: "Korean", code: "ko", value: "코드위드아즈란" },
  { language: "Arabic", code: "ar", value: "كودويذأزلان" },
  { language: "Chinese", code: "zh", value: "CODEWITHAZLAN" }, // typically stays English
  { language: "Hindi", code: "hi", value: "कोडविदअज़लान" },
  { language: "Bengali", code: "bn", value: "কোডউইথআজলান" },
  { language: "Punjabi", code: "pa", value: "ਕੋਡਵਿਥਅਜ਼ਲਾਨ" },
  { language: "Vietnamese", code: "vi", value: "CODEWITHAZLAN" },
  { language: "Indonesian", code: "id", value: "CODEWITHAZLAN" },
  { language: "Turkish", code: "tr", value: "CODEWITHAZLAN" },
  { language: "Persian", code: "fa", value: "کودویتھازلان" },
  { language: "Tamil", code: "ta", value: "கோட்விதஅஸ்லான்" },
  { language: "Telugu", code: "te", value: "కోడ్‌విత్‌అజ్లాన్" },
  { language: "Marathi", code: "mr", value: "कोडविथअज़लान" },
  { language: "Urdu", code: "ur", value: "کوڈوِدھازلٰان" },
  { language: "Swahili", code: "sw", value: "CODEWITHAZLAN" },
  { language: "Thai", code: "th", value: "โค้ดวิทอัซลาน" },
  { language: "Malay", code: "ms", value: "CODEWITHAZLAN" },
  { language: "Gujarati", code: "gu", value: "કોડવિથઅઝલાન" },
  { language: "Kannada", code: "kn", value: "ಕೋಡ್‌ವಿತ್ಅಝ್ಲಾನ್" },
  { language: "Malayalam", code: "ml", value: "കോഡ്‌വിഥ്അസ്ഡാന്" },
  { language: "Odia", code: "or", value: "କୋଡଵିଥଅଜଲାନ" },
  { language: "Sinhala", code: "si", value: "කෝඩ්විත්අස්ලාන්" },
  { language: "Pashto", code: "ps", value: "کوډوېتھازلاند" },
];
