import { LocaleType } from "@/constants/language";

// Define pages
export const NAV_ITEMS: {
  key: string;
  label: Record<LocaleType, string>;
}[] = [
  {
    key: "projects",
    label: {
      en: "Projects",
      es: "Proyectos",
      fr: "Projets",
      de: "Projekte",
      it: "Progetti",
      pt: "Projetos",
      ru: "Проекты",
      ja: "プロジェクト",
      ko: "프로젝트",
      ar: "المشاريع",
      zh: "项目",
      hi: "परियोजनाएँ",
      bn: "প্রকল্পসমূহ",
      pa: "ਪ੍ਰੋਜੈਕਟ",
      vi: "Dự án",
      id: "Proyek",
      tr: "Projeler",
      fa: "پروژه‌ها",
      ta: "திட்டங்கள்",
      te: "ప్రాజెక్టులు",
      mr: "प्रकल्प",
      ur: "منصوبے",
      sw: "Miradi",
      th: "โครงการ",
      ms: "Projek",
      gu: "પ્રોજેક્ટો",
      kn: "ಪ್ರಾಜೆಕ್ಟುಗಳು",
      ml: "പ്രോജക്ടുകൾ",
      or: "ପ୍ରକଳ୍ପଗୁଡିକ",
      si: "ප්‍රොජෙක්ට්",
      ps: "پروژې",
    },
  },
  {
    key: "blogs",
    label: {
      en: "Blogs",
      es: "Blogs",
      fr: "Blogs",
      de: "Blogs",
      it: "Blog",
      pt: "Blogs",
      ru: "Блоги",
      ja: "ブログ",
      ko: "블로그",
      ar: "مدونات",
      zh: "博客",
      hi: "ब्लॉग",
      bn: "ব্লগ",
      pa: "ਬਲੌਗ",
      vi: "Blog",
      id: "Blog",
      tr: "Bloglar",
      fa: "وبلاگ‌ها",
      ta: "பிளாக்கள்",
      te: "బ్లాగులు",
      mr: "ब्लॉग",
      ur: "بلاگز",
      sw: "Blogu",
      th: "บล็อก",
      ms: "Blog",
      gu: "બ્લોગ્સ",
      kn: "ಬ್ಲಾಗ್‌ಗಳು",
      ml: "ബ്ലോഗുകൾ",
      or: "ବ୍ଲଗ୍ସ",
      si: "බ්ලොග්",
      ps: "بلاګونه",
    },
  },
  {
    key: "about",
    label: {
      en: "About",
      es: "Acerca",
      fr: "À propos",
      de: "Über",
      it: "Informazioni",
      pt: "Sobre",
      ru: "О нас",
      ja: "約",
      ko: "소개",
      ar: "حول",
      zh: "关于",
      hi: "के बारे में",
      bn: "সম্পর্কে",
      pa: "ਬਾਰੇ",
      vi: "Giới thiệu",
      id: "Tentang",
      tr: "Hakkında",
      fa: "درباره",
      ta: "மிகவும்",
      te: "గురించి",
      mr: "बद्दल",
      ur: "کے بارے میں",
      sw: "Kuhusu",
      th: "เกี่ยวกับ",
      ms: "Tentang",
      gu: "વિશે",
      kn: "ಬಗ್ಗೆ",
      ml: "പറ്റി",
      or: "ବିଷୟରେ",
      si: " ගැන",
      ps: "په اړه",
    },
  },
];
